go-goyave/goyave

- install.sh
The install script (install.sh) wasn't working on macOS due to `sed -i` not been compatible and the use of `\e` instead of `\033`.
- Changed all `\e` to `\033`
- Changed `-i` to `-i.bak` and added `-exec rm {}.bak \;`. This works with both GNU sed and BSD sed.
None
None
> Update install.sh to work on macOS

- .github/workflows/test.yml
Run each independent continuous integration jobs in parallel, instead of sequentially, one after the other.
I'm not sure about the name for the `ineffassign` check.
The workflow file should maybe be renamed : `test.yml` to something else, `ci.yml` ?
A bit of duplication in the workflow file ? I'm sure there's a way around that.
Maybe you'll have to check the integration with coveralls.
And since I changed the workflow file, automated requirements for PRs will be a bit thrown off. Possible workarounds : 
- re-add the old tasks, merge, then change PRs' requirements, then remove the old tasks
- or temporarily disable PRs' requirements
None.
_(Really it's just boredom. I promise, next time I'll look at the open issues before)_
> Make independant CI jobs run in parallel

- docs_src/src/guide/basics/requests.md
- request.go
- router.go
- testsuite.go
Make a clear and detailed description of your changes, with the added benefits.
Adding an extra data to Request that would allow middleware to process data that is not part of the request's body
Example a new middleware that could wrap extra information to teh Request and later be processed.
`None`
List all related issues here:
* closes #117
> Adding extra data to request

- helper/map.go
I have added an alias to map[string]interface{} in the helper package.
This is useful when you want to create a long nested json response in the response.JSON function
If your pull request is functional (new utilities, helpers or middleware for example), **include some usage examples**.
For example:
Normally you would write the response as follows:
``` golang
response.JSON(200, map[string]interface{}{
"name": "Albert Shirima",
"website": "albertshirima.com",
"projects": []map[string]interface{}{
{
"name": "Goyave",
"is_contributor": true,
"meta": map[string]interface{}{
"website": "goyave.dev",
"contributors": 2,
},
},
},
})
```
With the helper struct:
``` golang
response.JSON(200, helper.Map{
"name": "Albert Shirima",
"website": "albertshirima.com",
"projects": []helper.Map{
{
"name": …
```
> Add a helper map useful for constructing a json response

- goyave_test.go
This commit change floats values to integers in goyave_test.go as we discussed in the #141 review
```go
// BEFORE
config.Set("server.port", 80.0)
// AFTER
config.Set("server.port", 80)
```
> floats to integers

- README.md
- config.test.json
- config/config.go
- database/config.test.json
- database/database.go
- resources/config.migration-test.json
Allow to set the entries of gorm.Config{}, from the config file.
(#147)  *Unable to set DisableForeignKeyConstraintWhenMigrating:*
As SQLite do not support constraints, when using associations in GORM models we get the following error
```
panic: constraints not implemented on sqlite, consider using DisableForeignKeyConstraintWhenMigrating, more details https://github.com/go-gorm/gorm/wiki/GORM-V2-Release-Note-Draft#all-new-migrator
```
To solve it we can modify our database config, by setting ``database.config.disableForeignKeyConstraintWhenMigrating`` to ``true`` :
```json
...
"database": {
"connection": "sqlite3",
"name": "dev.db",
"autoMigrate": true,
"config": {
"disableForeignKeyConstraintWhenMigrating": true
}
},
...
```
None
List all related issues here:
* #147
> Allow to set the entries of gorm.Config{}, from the config file.

- request.go
- request_test.go
The name parameter is unused inside the method
Name parameter in the Cookies method signature is unused.
Introduces breaking changes
> Remove name parameter in Cookies method

- go.mod
- go.sum
- testsuite.go
This PR updates the `ITestSuite interface` to be compatible with the next version of testify `v1.8.2` which adds a method to its `TestingSuite interface` which this mimics. Without this change, packages that depend on the newer testify library will cause a conflict at build time.
None. Since this interface is used internally, it should not impact other packages that depend on either testify version.
None
> fixed interface compatibility issues with testify v1.8.2

- log/log.go
- middleware/compress/compress.go
- middleware/compress/compress_test.go
- response.go
- response_test.go
**Issue(s):** closes #215
- Make `Response` implement `http.Flusher`
- Call `PreWrite` only once on the first `Write`
- Add `CommonWriter` to reduce chained writers boilerplate
- Use `CommonWriter` for log and compress middleware
> #215 - Response: add support for flushing

- lang/default.go
- middleware/parse/parse.go
- middleware/parse/parse_test.go
- request.go
- response.go
- router.go
- status_handler.go
- status_handler_test.go
**Issue(s):** closes #216  
As per discusion in Discord, I've added a message when the parser returns a `400` bad request when Content-Type JSON is given, but no, or an invalid body. I've handled this via `response.Extra[goyave.ExtraRequestError{}]`. 
It also translates.
Let me know :)
> #216 - Add message to request (extra) and handle in status handler

- go.sum
- middleware/compress/brotli.go
- middleware/compress/brotli_test.go
- middleware/compress/lzw.go
- middleware/compress/lzw_test.go
- middleware/compress/zlib.go
- middleware/compress/zlib_test.go
- middleware/compress/zstd.go
- middleware/compress/zstd_test.go
Issue(s): #197, #198, #199, #200
This pull request provides new Encoders for the Goyave compress middleware using the following algorithms:
- Zlib (deflate)
- LZW
- Brotli
- Zstd
Tests and comments are included
> Support middleware compression with Zlib, LZW, Brotli, and Zstd encoders

- auth/jwt_controller.go
- auth/jwt_controller_test.go
**Issue(s):** #221 
Fixed a reflection error in the Login handler of the JWT Controller. If the user service returns `gorm.ErrRecordNotFound`, a `401 Unauthorized` response will be returned.
> #221 Auth: Fix JWT controller gorm.ErrRecordNotFound handling

- slog/slog.go
- slog/slog_test.go
- util/testutil/testutil.go
- util/testutil/testutil_test.go
**Issue(s):** #228    
**Discussion:**  no discussion
Created the logger with `io.Discard` and set it as the default in NewTestServerWithOptions if no logger is provided as a parameter.
I noticed that `io.Discard` is already used [here in log_bench_test.go](https://github.com/go-goyave/goyave/blob/2ce8e01d18639caf00098200b28d973b2420d7b4/log/log_bench_test.go#L17) in a `slog.NewHandler`. In the implementation of `slog.Discard` I chose to use `slog.NewTextHandler` because I understand that it achieves the same objective, however it is more evident that it is a text.
> #228 - Feat: create slog discard logger

- middleware.go
- middleware_test.go
- validation/validator.go
- validation/validator_test.go
**Issue(s):** none
- Added a `context.Context` field to the `validation.Options` and `validation.Context` structures. If not provided, it defaults to `context.Background()`.
- The built-in validation middleware now uses the request context in the validation options.
- The DB instance used in the validation options by the built-in validation middleware was already injected with the request context. Custom validators don't need to be updated.
- Places where manual validation is used may need to be updated. However, those will continue to work exactly like they used to without changing anything.
> Validation: add context.Context to validation options

- response.go
- response_test.go
- util/fsutil/fsutil.go
- util/fsutil/fsutil_test.go
- Open file once instead of thrice in `response.File()` and `response.Download()`
- `fsutil`: expanded the list of known extensions for content type detection
- `fsutil`: add `DetectContentType` to sniff from a reader directly
- `fsutil`: add `DetectContentTypeByExtension` for content type detection fallback
> Response: optimize writeFile

- util/testutil/session.go
- util/testutil/session_test.go
**Issue(s):** closes #233 
`testutil.Session` is a new testing utility used to mock the `session.Session` interface. This implementation is designed to provide a realistic, observable transaction system and help identify incorrect usage. You can find more details in the godoc on the `testutil.Session` struct.
**Usage example**:
```go
session := testutil.NewTestSession()
service := NewService(repo, session)
createDTO := &dto.CreateUserRequest{
//...
}
created, err := service.Create(context.Background(), createDTO)
require.NoError(t, err)
expected := &dto.User{
//...
}
assert.Equal(t, expected, created)
txs := session.Children()
if assert.Len(t, txs, 1) {
assert.Equal(t, testutil.SessionCommitted, txs[0].Status())
}
```
- The incorrect session usage detection is quite strict and may force …
> testutil: add Session

- validation/ruleset.go
- validation/ruleset_test.go
- validation/unique_test.go
- validation/validator.go
**Issue(s):** closes #239
- Added an unexported `Init()` method on `validation.Validator` and implement it in `BaseValidator`.
- This allows initializing a `Validator` inside tests.
- This method can be overridden by developers in custom validators in case some additional custom values must be defined at initialization.
- The composition with `BaseValidator` is still mandatory. This decision was initially made to promote a simpler and shorter syntax for custom validator, by taking advantage of method overriding.
None.
> Validation: add exported Init to Validator interface #239

- validation/ruleset.go
- validation/ruleset_test.go
None.
Fixed "illegal syntax" error when using ruleset composition for an array of objects. Example:
```go
func SomeValidation(r *goyave.Request) v.RuleSet {
return v.RuleSet{
{Path: v.CurrentElement, Rules: v.List{v.Object()}},
{Path: "someArray", Rules: CompositionValidation(r)}},
}
}
func CompositionValidation(_ *goyave.Request) v.RuleSet {
return v.RuleSet{
{Path: v.CurrentElement, Rules: v.List{v.Array()}},
{Path: "[]", Rules: v.List{v.Object()}},
{Path: "[].field", Rules: v.List{v.Required(), v.String()}},
}
}
```
This would result in the following error before the fix:
```
illegal syntax: "someArray.[].field"
```
The path that should be actually generated is `someArray[].field` (without the extra dot before the brackets).
None.
> Validation: fix illegal path syntax error with composition

- validation/only_if.go
- validation/only_if_test.go
**Issue(s):** closes #245 
Added the `OnlyIf` wrapper validator, which enables conditional validation for complex use-cases. The validation message, placeholders and other data from the wrapped validator are kept and "inherited" automatically.
For example, if you want a validator to be executed only if another boolean field is "true":
```go
v.OnlyIf(func(ctx *v.Context) bool {
other := walk.MustParse("other").First(ctx.Data)
return other.Value == true
}, MyValidator())
```
This validator cannot be used with `Required()`, `RequiredIf()`, `Nullable()` or any type validator validators. Using it with these validators may lead to buggy behavior. This use-case shouldn't be encouraged anyway as it would make the request body difficult to use and convert to a DTO afterwards.
> validation: add OnlyIfValidator

- lang/lang_test.go
- middleware_test.go
- resources/lang/en-US/rules.json
- validation/comparison.go
- validation/date.go
- validation/different.go
- validation/in.go
- validation/regex.go
- validation/required.go
- validation/ruleset.go
- validation/same.go
- validation/unique.go
- validation/validator.go
- validation/validator_test.go
**Issue(s):** closes #250
- Added `validation.WithMessage()` function, which overrides the language entry used to render the error message of a validator.
- Original placeholders returned by the validator are still used to render the message.
- Type-dependent and "element" suffixes are not added when the message is overridden. 
**Example usage:**
```go
func (ctrl *Controller) UpdateRequest(_ *goyave.Request) v.RuleSet {
return v.RuleSet{
//...
{Path: "contents", Rules: v.List{v.WithMessage(v.String(), "validation.rules.custom"), v.Min(10)}},
}
}
```
The `WithMessage` syntax is not the cleanest. However, using a method instead wouldn't be possible because it would need to return itself, which wouldn't be possible with composition.
> Validation: add WithMessage

- .github/workflows/test.yml
- util/typeutil/undefined.go
- util/typeutil/undefined_test.go
**Issue(s):** none
**Discussion:** none
- With the introduction of the json `omitzero` tag in [Go 1.24](https://tip.golang.org/doc/go1.24), the `typeutil.Undefined` type can be improved to support json marshaling. If used in combination with the `omitzero` tag, the marshaling behavior will be as expected for a non-present field.
- Adds the `Set` and `Unset` convenience methods.
- Improves documentation of the `typeutil.Undefined` type.
- Handle more cases in the `Scan()` implementation
- If the `src` is also an `Undefined` (or `*Undefined`) of the same `T`, use its `Val` directly
- If `src` is nil, set the `Val` to `T`'s zero value
- Prevent nil dereferences if the `src` is a pointer. Use `T`'s zero value instead and still consider the field as present. The idea is to always consider the …
> typeutil: Undefined improvements
